### PR TITLE
Add NFT page description. Names update from web wallet to nodleprotocol.io 

### PR DESCRIPTION
**Pull request by Douglasacost**
What changes here:
Added nft page description and update the main page description for the Nodle web wallet

Re-named: 
Since the word "Web wallet" can mislead the user to our Web Wallet(https://wallet.nodle.com/), this name outside the context has changed
Web Wallet => Nodle account
Web Wallet => nodleprotocol.io (Substrate Portal)
depends on the context

### CODE REVIEW

**Review by ETeissonniere — APPROVED** [review]

**Comment by spacesmutje** [comment]
The web wallet should also support QR codes, to make sending funds from the Nodle Cash app to the web wallet more convenient.

**Comment by Douglasacost** [comment]
I've arrange a new task to add the QR code @spacesmutje

**Comment by spacesmutje** [comment]
Thanks a lot! GitHub is still new to me. Not quiet sure when to PR or Issue.

**Comment by Douglasacost** [comment]
No worries, thanks for comment @spacesmutje

**Pull request merged**
